spring.application.name=ai-support-intelligence-platform

#LLM props
openai.api.key=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 
openai.api.url=https://openrouter.ai/api/v1/chat/completions


#Cache props
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#DB Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_support_db
spring.datasource.username=aniket
spring.datasource.password=aniket123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#Kafka props
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ticket-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*