spring.application.name=demoapp


openai.api.key=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
openai.api.url=https://openrouter.ai/api/v1/chat/completions

spring.cache.type=redis

spring.data.redis.host=localhost
spring.data.redis.port=6379

#DB Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_support_db
spring.datasource.username=aniket
spring.datasource.password=aniket123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC